name: Build and Release
on:
  push:
    branch: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # Required for attestation
      attestations: write # Required for attestation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: {node-version: 'lts/*', cache: 'npm'}
      - run: npm ci
      - run: npm run build
      - uses: actions/attest-build-provenance@v4
        with:
          subject-path: 'main.js' # Add other files (manifest.json, styles.css) here
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            main.js
            manifest.json
            styles.css